/*
 * This file is part of BungeeGuard, licensed under the MIT License.
 *
 *  Copyright (c) lucko (Luck) <luck@lucko.me>
 *  Copyright (c) contributors
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to deal
 *  in the Software without restriction, including without limitation the rights
 *  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *  copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included in all
 *  copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  SOFTWARE.
 */

package me.lucko.bungeeguard.backend;

import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

/**
 * A store of allowed tokens.
 */
public class TokenStore {
    private final BungeeGuardBackend plugin;
    private Set<String> allowedTokens = Collections.emptySet();

    public TokenStore(BungeeGuardBackend plugin) {
        this.plugin = plugin;
    }

    public void reload() {
        this.plugin.reloadConfig();
        load();
    }

    public void load() {
        this.allowedTokens = new HashSet<>(this.plugin.getTokens());
    }

    /**
     * Gets if a token is allowed.
     *
     * @param token the token
     * @return true if allowed
     */
    public boolean isAllowed(String token) {
        return this.allowedTokens.contains(token);
    }

    /**
     * Has the server owner bothered to configure their tokens correctly...?
     *
     * @return true if BungeeGuard has not yet been configured
     */
    public boolean isUsingDefaultConfig() {
        return this.allowedTokens.contains("the token generated by the proxy goes here") ||
                this.allowedTokens.contains("you can add as many as you like.");
    }

}
